import rhinoscriptsyntax as rs

names = ['2B?',
'3B11B',
'3B9',
'3B?',
'3C20',
'3C21',
'3C22',
'3C23',
'3C24',
'3CA1',
'4A?',
'4B?',
'5A10',
'5A11',
'5A?',
'5B11',
'5B4?',
'5B?',
'6A21A',
'6A?',
'6B22',
'6B23',
'6B?',
'6D10',
'6D11',
'7C?',
'8C',
'8C4?',
'8C5s',
'8C6?',
'8C?',
'9C20',
'9C21',
'9C5A',
'9C5B',
'9D?',
'9E?',
'9EB?',
'9F3M?',
'9F?',
'9FB?',
'9G?',
'?',
'A19?',
'A70',
'A70A',
'A71',
'A71A',
'A72',
'A72A',
'A73',
'A74',
'A?',
'AG?',
'AR?',
'B102',
'B102?',
'B17B',
'B35?',
'B70',
'B70A',
'B71A',
'B79',
'B79A',
'B80A',
'B81',
'B81A',
'B82A',
'B83',
'B84',
'B86',
'B86A',
'B87A',
'B88',
'B88A',
'B89A',
'B92',
'B93',
'B94',
'B94A',
'B95A',
'B98',
'B?',
'B?A',
'FSC',
'Q?',
'S2',
'S2??',
'W?'
]

dots = rs.GetObjects()

rs.EnableRedraw(False)
for d in dots:
    name = rs.TextDotText(d)
    if name in names:
        rs.ObjectLayer(d, layer="SCOPE_new")



rs.EnableRedraw(True)

